spring:

  application:
    name: cyberpulse-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/cyberpulse
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:0328}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

    open-in-view: false

    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

  endpoint:
    health:
      show-details: when_authorized

logging:
  level:
    root: INFO
    com.cyberpulse: DEBUG

jwt:
  secret: ${JWT_SECRET:wyv6SnkAf/easwF3mXcCBwVaJ4oflZzqYBmPC08hECcxbKGjSyB9i7rRnrVc+LqwhnlMG9CYoukCkolV6yJ7hA==}
  access-token-expiration: 900000
  refresh-token-expiration: 604800000